[2022-03-18 02:58:18,206] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: demo_pipeline.document_etl manual__2022-03-17T19:32:45.886946+00:00 [queued]>
[2022-03-18 02:58:18,220] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: demo_pipeline.document_etl manual__2022-03-17T19:32:45.886946+00:00 [queued]>
[2022-03-18 02:58:18,220] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-18 02:58:18,221] {taskinstance.py:1244} INFO - Starting attempt 12 of 12
[2022-03-18 02:58:18,222] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-18 02:58:18,267] {taskinstance.py:1264} INFO - Executing <Task(SparkSubmitOperator): document_etl> on 2022-03-17 19:32:45.886946+00:00
[2022-03-18 02:58:18,270] {standard_task_runner.py:52} INFO - Started process 67 to run task
[2022-03-18 02:58:18,272] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'demo_pipeline', 'document_etl', 'manual__2022-03-17T19:32:45.886946+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/demo.py', '--cfg-path', '/tmp/tmpjxmrngx0', '--error-file', '/tmp/tmp8r8m31ob']
[2022-03-18 02:58:18,274] {standard_task_runner.py:77} INFO - Job 26: Subtask document_etl
[2022-03-18 02:58:18,350] {logging_mixin.py:109} INFO - Running <TaskInstance: demo_pipeline.document_etl manual__2022-03-17T19:32:45.886946+00:00 [running]> on host 12925515a057
[2022-03-18 02:58:18,416] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=demo_pipeline
AIRFLOW_CTX_TASK_ID=document_etl
AIRFLOW_CTX_EXECUTION_DATE=2022-03-17T19:32:45.886946+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-17T19:32:45.886946+00:00
[2022-03-18 02:58:18,425] {base.py:70} INFO - Using connection to: id: spark_default. Host: spark://spark-master, Port: 7077, Schema: , Login: , Password: None, extra: {'queue': 'root.default'}
[2022-03-18 02:58:18,427] {spark_submit.py:335} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --name demo --queue root.default //usr/local/share_storages/spark_jobs/demo/job.py
[2022-03-18 02:58:19,809] {spark_submit.py:488} INFO - WARNING: An illegal reflective access operation has occurred
[2022-03-18 02:58:19,810] {spark_submit.py:488} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/usr/local/lib/python3.9/site-packages/pyspark/jars/spark-unsafe_2.12-3.2.1.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2022-03-18 02:58:19,811] {spark_submit.py:488} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2022-03-18 02:58:19,812] {spark_submit.py:488} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2022-03-18 02:58:19,813] {spark_submit.py:488} INFO - WARNING: All illegal access operations will be denied in a future release
[2022-03-18 02:58:20,291] {spark_submit.py:488} INFO - Job1 say hello!
[2022-03-18 02:58:20,775] {spark_submit.py:488} INFO - 2022-03-18 02:58:20.775386: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
[2022-03-18 02:58:20,776] {spark_submit.py:488} INFO - 2022-03-18 02:58:20.775451: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[2022-03-18 02:58:23,052] {spark_submit.py:488} INFO - Traceback (most recent call last):
[2022-03-18 02:58:23,053] {spark_submit.py:488} INFO - File "/usr/local/share_storages/spark_jobs/demo/job.py", line 7, in <module>
[2022-03-18 02:58:23,054] {spark_submit.py:488} INFO - from PIL import Image
[2022-03-18 02:58:23,055] {spark_submit.py:488} INFO - ModuleNotFoundError: No module named 'PIL'
[2022-03-18 02:58:23,364] {spark_submit.py:488} INFO - log4j:WARN No appenders could be found for logger (org.apache.spark.util.ShutdownHookManager).
[2022-03-18 02:58:23,366] {spark_submit.py:488} INFO - log4j:WARN Please initialize the log4j system properly.
[2022-03-18 02:58:23,366] {spark_submit.py:488} INFO - log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[2022-03-18 02:58:23,418] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/usr/local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 419, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --name demo --queue root.default //usr/local/share_storages/spark_jobs/demo/job.py. Error code is: 1.
[2022-03-18 02:58:23,424] {taskinstance.py:1272} INFO - Marking task as FAILED. dag_id=demo_pipeline, task_id=document_etl, execution_date=20220317T193245, start_date=20220318T025818, end_date=20220318T025823
[2022-03-18 02:58:23,471] {standard_task_runner.py:89} ERROR - Failed to execute job 26 for task document_etl
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/usr/local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 419, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --name demo --queue root.default //usr/local/share_storages/spark_jobs/demo/job.py. Error code is: 1.
[2022-03-18 02:58:23,490] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-18 02:58:23,515] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
